import { cliArgv, settingsArgv, type AdapterContext } from "../types.js";

export interface PythonExtensionOptions {
  /** GI namespace: "Nautilus" or "Caja". */
  module: string;
  /** Typelib versions to try, newest first. */
  versions: string[];
  /** Name used in the generated docstring (`syncdrop integrate install <name>`). */
  installName: string;
}

/**
 * Python file-manager extension (nautilus-python / python-caja share one API).
 * The folders and key settings come from `syncdrop menu --json` each time the menu opens,
 * so changes made in the settings appear without reinstalling.
 */
export function buildPythonExtension(ctx: AdapterContext, o: PythonExtensionOptions): string {
  const cmd = JSON.stringify(cliArgv(ctx.cli));
  const settingsCmd = JSON.stringify(settingsArgv(ctx.cli));
  const [first, second] = o.versions;
  const requireVersion = second
    ? `try:
    gi.require_version("${o.module}", "${first}")
    _VER = "${first}"
except ValueError:
    gi.require_version("${o.module}", "${second}")
    _VER = "${second}"`
    : `gi.require_version("${o.module}", "${first}")
_VER = "${first}"`;
  return `"""SyncDrop context menu for ${o.module}. Generated by 'syncdrop integrate install ${o.installName}'."""
import json
import subprocess

import gi

${requireVersion}
from gi.repository import GObject, ${o.module}

# Load the GDK/GTK generation that matches the file manager, never the other one.
if _VER == "4.0":
    gi.require_version("Gdk", "4.0")
    from gi.repository import Gdk
else:
    gi.require_version("Gdk", "3.0")
    gi.require_version("Gtk", "3.0")
    from gi.repository import Gdk, Gtk

SYNCDROP_CMD = ${cmd}
SETTINGS_CMD = ${settingsCmd}


def _held():
    """(ctrl, shift) held right now; (False, False) when it cannot be told."""
    try:
        if _VER == "4.0":
            state = Gdk.Display.get_default().get_default_seat().get_keyboard().get_modifier_state()
        else:
            ok, state = Gtk.get_current_event_state()
            if not ok:
                state = Gdk.Keymap.get_for_display(Gdk.Display.get_default()).get_modifier_state()
        return bool(state & Gdk.ModifierType.CONTROL_MASK), bool(state & Gdk.ModifierType.SHIFT_MASK)
    except Exception:
        return False, False


def _menu():
    try:
        out = subprocess.run(
            SYNCDROP_CMD + ["menu", "--json"],
            capture_output=True, text=True, timeout=10, check=True,
        ).stdout
        return json.loads(out)
    except Exception:
        return {"folders": [], "modifiers": {}}


class SyncDropExtension(GObject.GObject, ${o.module}.MenuProvider):
    def _send(self, _item, target_id, modifiers, paths):
        # Shift = link and Ctrl = move when those keys are enabled; both held: the harmless one (link) wins.
        ctrl, shift = _held()
        operation = "copy"
        if shift and modifiers.get("shift"):
            operation = modifiers["shift"]
        elif ctrl and modifiers.get("ctrl"):
            operation = modifiers["ctrl"]
        subprocess.Popen(
            SYNCDROP_CMD
            + ["add", "--target", target_id, "--operation", operation, "--conflict", "keep-both", "--notify", "--"]
            + paths
        )

    def get_file_items(self, *args):
        files = args[-1]  # newer API: (files); older API: (window, files)
        paths = []
        for f in files:
            loc = f.get_location()
            p = loc.get_path() if loc is not None else None
            if p:
                paths.append(p)
        if not paths:
            return []
        model = _menu()
        entries = model.get("folders", [])
        modifiers = model.get("modifiers", {})
        if not entries:
            return []
        root = ${o.module}.MenuItem(name="SyncDrop::Root", label="SyncDrop")
        menu = ${o.module}.Menu()
        root.set_submenu(menu)
        for e in entries:
            item = ${o.module}.MenuItem(name="SyncDrop::" + e["target"], label=e["label"])
            item.connect("activate", self._send, e["target"], modifiers, paths)
            menu.append_item(item)
        settings = ${o.module}.MenuItem(name="SyncDrop::Settings", label="Settings")
        settings.connect("activate", lambda _item: subprocess.Popen(SETTINGS_CMD))
        menu.append_item(settings)
        return [root]
`;
}
