import { cliArgv, settingsArgv, type AdapterContext } from "../types.js";

export interface PythonExtensionOptions {
  /** GI namespace: "Nautilus" or "Caja". */
  module: string;
  /** Typelib versions to try, newest first. */
  versions: string[];
  /** Name used in the generated docstring (`syncdrop integrate install <name>`). */
  installName: string;
}

/**
 * Python file-manager extension (nautilus-python / python-caja share one API).
 * The entries come from `syncdrop menu --json` each time the menu opens,
 * so changes made in the settings appear without reinstalling.
 */
export function buildPythonExtension(ctx: AdapterContext, o: PythonExtensionOptions): string {
  const cmd = JSON.stringify(cliArgv(ctx.cli));
  const settingsCmd = JSON.stringify(settingsArgv(ctx.cli));
  const [first, second] = o.versions;
  const requireVersion = second
    ? `try:
    gi.require_version("${o.module}", "${first}")
except ValueError:
    gi.require_version("${o.module}", "${second}")`
    : `gi.require_version("${o.module}", "${first}")`;
  return `"""SyncDrop context menu for ${o.module}. Generated by 'syncdrop integrate install ${o.installName}'."""
import json
import subprocess

import gi

${requireVersion}
from gi.repository import GObject, ${o.module}

SYNCDROP_CMD = ${cmd}
SETTINGS_CMD = ${settingsCmd}


def _entries():
    try:
        out = subprocess.run(
            SYNCDROP_CMD + ["menu", "--json"],
            capture_output=True, text=True, timeout=10, check=True,
        ).stdout
        return json.loads(out)
    except Exception:
        return []


class SyncDropExtension(GObject.GObject, ${o.module}.MenuProvider):
    def _send(self, _item, target_id, operation, paths):
        subprocess.Popen(
            SYNCDROP_CMD
            + ["add", "--target", target_id, "--operation", operation, "--conflict", "keep-both", "--notify", "--"]
            + paths
        )

    def get_file_items(self, *args):
        files = args[-1]  # newer API: (files); older API: (window, files)
        paths = []
        for f in files:
            loc = f.get_location()
            p = loc.get_path() if loc is not None else None
            if p:
                paths.append(p)
        if not paths:
            return []
        entries = _entries()
        if not entries:
            return []
        root = ${o.module}.MenuItem(name="SyncDrop::Root", label="SyncDrop")
        menu = ${o.module}.Menu()
        root.set_submenu(menu)
        for e in entries:
            item = ${o.module}.MenuItem(name="SyncDrop::" + e["target"] + "::" + e["operation"], label=e["label"])
            item.connect("activate", self._send, e["target"], e["operation"], paths)
            menu.append_item(item)
        settings = ${o.module}.MenuItem(name="SyncDrop::Settings", label="Settings")
        settings.connect("activate", lambda _item: subprocess.Popen(SETTINGS_CMD))
        menu.append_item(settings)
        return [root]
`;
}
