import type { AdapterContext } from "../types.js";

export interface PythonExtensionOptions {
  /** GI namespace: "Nautilus" or "Caja". */
  module: string;
  /** Typelib versions to try, newest first. */
  versions: string[];
  /** Name used in the generated docstring (`syncdrop integrate install <name>`). */
  installName: string;
}

/**
 * Python file-manager extension (nautilus-python / python-caja share one API).
 * The target list comes from `syncdrop targets --json` each time the menu opens,
 * so new targets appear without reinstalling.
 */
export function buildPythonExtension(ctx: AdapterContext, o: PythonExtensionOptions): string {
  const cmd = JSON.stringify([ctx.cli.node, ctx.cli.script]);
  const [first, second] = o.versions;
  const requireVersion = second
    ? `try:
    gi.require_version("${o.module}", "${first}")
except ValueError:
    gi.require_version("${o.module}", "${second}")`
    : `gi.require_version("${o.module}", "${first}")`;
  return `"""SyncDrop context menu for ${o.module}. Generated by 'syncdrop integrate install ${o.installName}'."""
import json
import subprocess

import gi

${requireVersion}
from gi.repository import GObject, ${o.module}

SYNCDROP_CMD = ${cmd}


def _targets():
    try:
        out = subprocess.run(
            SYNCDROP_CMD + ["targets", "--json"],
            capture_output=True, text=True, timeout=10, check=True,
        ).stdout
        return json.loads(out)
    except Exception:
        return []


class SyncDropExtension(GObject.GObject, ${o.module}.MenuProvider):
    def _send(self, _item, target_id, paths):
        subprocess.Popen(
            SYNCDROP_CMD
            + ["add", "--target", target_id, "--conflict", "keep-both", "--notify", "--"]
            + paths
        )

    def get_file_items(self, *args):
        files = args[-1]  # newer API: (files); older API: (window, files)
        paths = []
        for f in files:
            loc = f.get_location()
            p = loc.get_path() if loc is not None else None
            if p:
                paths.append(p)
        if not paths:
            return []
        targets = _targets()
        if not targets:
            return []
        root = ${o.module}.MenuItem(name="SyncDrop::Root", label="SyncDrop")
        menu = ${o.module}.Menu()
        root.set_submenu(menu)
        for t in targets:
            item = ${o.module}.MenuItem(name="SyncDrop::Target::" + t["id"], label=t["name"])
            item.connect("activate", self._send, t["id"], paths)
            menu.append_item(item)
        return [root]
`;
}
