import { access, mkdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { which } from "../../../shared/paths.js";
import { xdgDataHome } from "../../common.js";
import type { AdapterContext, AdapterReport, FileManagerAdapter } from "../../types.js";

/**
 * nautilus-python extension. The target list is read from `syncdrop targets --json`
 * each time the menu opens, so new targets appear without reinstalling.
 */
export function buildExtension(ctx: AdapterContext): string {
  const cmd = JSON.stringify([ctx.cli.node, ctx.cli.script]);
  return `"""SyncDrop context menu for Nautilus. Generated by 'syncdrop integrate install nautilus'."""
import json
import subprocess

import gi

try:
    gi.require_version("Nautilus", "4.0")
except ValueError:
    gi.require_version("Nautilus", "3.0")
from gi.repository import GObject, Nautilus

SYNCDROP_CMD = ${cmd}


def _targets():
    try:
        out = subprocess.run(
            SYNCDROP_CMD + ["targets", "--json"],
            capture_output=True, text=True, timeout=10, check=True,
        ).stdout
        return json.loads(out)
    except Exception:
        return []


class SyncDropExtension(GObject.GObject, Nautilus.MenuProvider):
    def _send(self, _item, target_id, paths):
        subprocess.Popen(
            SYNCDROP_CMD
            + ["add", "--target", target_id, "--conflict", "keep-both", "--notify", "--"]
            + paths
        )

    def get_file_items(self, *args):
        files = args[-1]  # Nautilus 4: (files); Nautilus 3: (window, files)
        paths = []
        for f in files:
            loc = f.get_location()
            p = loc.get_path() if loc is not None else None
            if p:
                paths.append(p)
        if not paths:
            return []
        targets = _targets()
        if not targets:
            return []
        root = Nautilus.MenuItem(name="SyncDrop::Root", label="SyncDrop")
        menu = Nautilus.Menu()
        root.set_submenu(menu)
        for t in targets:
            item = Nautilus.MenuItem(name="SyncDrop::Target::" + t["id"], label=t["name"])
            item.connect("activate", self._send, t["id"], paths)
            menu.append_item(item)
        return [root]
`;
}

const EXTENSION_LIBS = [
  "/usr/lib64/nautilus/extensions-4",
  "/usr/lib/nautilus/extensions-4",
  "/usr/lib/x86_64-linux-gnu/nautilus/extensions-4",
  "/usr/lib/aarch64-linux-gnu/nautilus/extensions-4",
  "/usr/lib64/nautilus/extensions-3.0",
  "/usr/lib/nautilus/extensions-3.0",
  "/usr/lib/x86_64-linux-gnu/nautilus/extensions-3.0",
];

async function hasNautilusPython(): Promise<boolean> {
  for (const dir of EXTENSION_LIBS) {
    try {
      await access(path.join(dir, "libnautilus-python.so"));
      return true;
    } catch {
      /* next */
    }
  }
  return false;
}

export class NautilusAdapter implements FileManagerAdapter {
  readonly name = "nautilus" as const;
  constructor(private readonly ctx: AdapterContext) {}

  private get file(): string {
    return path.join(xdgDataHome(), "nautilus-python", "extensions", "syncdrop.py");
  }

  isSupported = async () => process.platform === "linux" && !!(await which("nautilus"));

  async install(): Promise<AdapterReport> {
    await mkdir(path.dirname(this.file), { recursive: true });
    await writeFile(this.file, buildExtension(this.ctx));
    const notes = ["Restart Nautilus: nautilus -q"];
    if (!(await hasNautilusPython())) {
      notes.unshift("WARNING: nautilus-python not found. Install it (Fedora: python3-nautilus, Debian/Ubuntu/Zorin: python3-nautilus).");
    }
    return { files: [this.file], notes };
  }

  async uninstall(): Promise<AdapterReport> {
    await rm(this.file, { force: true });
    return { files: [this.file], notes: ["Restart Nautilus: nautilus -q"] };
  }
}
